online_ordering_enabled: true
social_media:
  facebook_url: https://www.facebook.com/The-Bottle-Room-122821818112/
  twitter_url: https://twitter.com/thebottleroom
  instagram_url: https://www.instagram.com/thebottleroom/
  yelp_url: http://www.yelp.com/biz/the-bottle-room-whittier
location:
  phone_number: 562-696-8000
  fax: 626-389-5407
  address_line_1: 6741 Greenleaf Avenue
  address_line_2: Whittier, CA 90601
  email: info@thebottleroombar.com
send_contact_to: dan@cubicflow.com
ordering_disabled_notice: Ordering is disabled
